CRITICAL - 2023-11-18 04:53:23 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\UserController.php(9): view('register')
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\UserController->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-18 04:54:15 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\UserController.php(9): view('register')
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\UserController->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-18 05:34:51 --> Call to undefined function baseUrl()
in APPPATH\Views\public_layout.php on line 9.
 1 SYSTEMPATH\View\View.php(226): include()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('public_layout', [], true)
 4 APPPATH\Controllers\UserController.php(9): view('public_layout')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\UserController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-18 05:35:18 --> Call to undefined function baseURL()
in APPPATH\Views\public_layout.php on line 9.
 1 SYSTEMPATH\View\View.php(226): include()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('public_layout', [], true)
 4 APPPATH\Controllers\UserController.php(9): view('public_layout')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\UserController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-18 15:16:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4-app-test\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-app-test\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-app-test\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-app-test\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-app-test\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-app-test\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-app-test\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-app-test\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-app-test\app\Controllers\UserController.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-app-test\system\CodeIgniter.php(919): App\Controllers\UserController->userRegistration()
#9 C:\xampp\htdocs\codeigniter4-app-test\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#10 C:\xampp\htdocs\codeigniter4-app-test\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-app-test\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\codeigniter4-app-test\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-app-test\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-app-test\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-app-test\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-app-test\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\codeigniter4-app-test\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\codeigniter4-app-test\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\codeigniter4-app-test\app\Controllers\UserController.php(40): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\codeigniter4-app-test\system\CodeIgniter.php(919): App\Controllers\UserController->userRegistration()
#8 C:\xampp\htdocs\codeigniter4-app-test\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\codeigniter4-app-test\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-app-test\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-11-18 15:16:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`username`, `email`, `password`, `mobile`, `user_profile`) VALUES (:username:, :email:, :password:, :mobile:, :user_profile:)', [...], false)
 3 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\UserController.php(40): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\UserController->userRegistration()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
